# Generated by Django 4.1.7 on 2023-06-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item'},
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
