# Generated by Django 4.1.7 on 2023-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
