# Generated by Django 4.1.7 on 2023-06-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(db_index=True, default=1),
        ),
    ]
