# Generated by Django 4.1.7 on 2023-06-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menuitem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
