# Generated by Django 4.1.7 on 2023-06-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order item'},
        ),
    ]
