# Generated by Django 4.1.7 on 2023-06-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_price',
        ),
    ]
