# Generated by Django 4.1.7 on 2023-06-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
